- src: https://github.com/EfimovEO/ansible_role_docker_install.git
  version: main
  name: docker_install

- src: https://github.com/EfimovEO/ansible_role_nginx.git         
  version: main
  name: nginx 

- src: https://github.com/EfimovEO/ansible_role_web_app.git
  version: main
  name: web_app



